# Generated by Django 5.0.6 on 2024-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
