# Generated by Django 5.0.6 on 2024-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='kitoblar', to='demo.author'),
        ),
    ]
