# Generated by Django 5.0.6 on 2024-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_book_published_at_alter_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
