# Generated by Django 5.0.6 on 2024-06-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_sale_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('card', 'Karta'), ('loan', 'Nasiya')], max_length=4, verbose_name="To'lov turi"),
        ),
    ]
