# Generated by Django 5.0.6 on 2024-06-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_alter_sale_price_alter_sale_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(help_text='Bu yerdan kitobni tanla', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='demo.book'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.PositiveIntegerField(default=0, help_text='Bu yerga sotilgan sonini kirit', verbose_name='Sotilgan soni'),
        ),
    ]
