# Generated by Django 5.0.6 on 2024-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Vazifa')),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('started', 'Jarayonda'), ('finished', 'Tugatilgan')], max_length=16)),
            ],
        ),
    ]
